# Generated by Django 5.2.1 on 2025-05-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_updated_at'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='no_past_events_unless_completed',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='published', max_length=10),
        ),
    ]
