# Generated by Django 5.2.1 on 2025-05-31 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_event_no_past_events_unless_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Title must be at least 3 characters long.')]),
        ),
    ]
