# Generated by Django 5.2.1 on 2025-06-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_event_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(help_text='Event date.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Detailed description of the event.', max_length=1000),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(help_text='Event venue or address.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(help_text='Event start time.'),
        ),
    ]
