services:
  db:
    image: postgres:16
    restart: always
    env_file:
      - .env.docker.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - webnet

  web:
    build: .
    restart: unless-stopped
    command: >
      sh -c "./wait-for-it.sh db:5432 --
         python manage.py migrate --no-input &&
         python manage.py collectstatic --no-input &&
         gunicorn --workers ${GUNICORN_WORKERS:-9} --threads ${GUNICORN_THREADS:-4} --bind 0.0.0.0:8000 event_manager.wsgi:application"
    env_file:
      - .env.docker.prod
    depends_on:
      - db
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
    networks:
      - webnet

volumes:
  postgres_data_prod:

networks:
  webnet:
    driver: bridge