services:
  db:
    image: postgres:16
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - .env.docker.dev

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app   # live-reload при зміні файлів (DEV)
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker.dev

volumes:
  postgres_data_dev:

