services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data

  web:
    build: .
    restart: unless-stopped
    # Чекаємо DB потім запускаємо міграції, collectstatic і gunicorn
    command: >
      sh -c "./wait-for-it.sh db:5432 -- python manage.py migrate --no-input &&
             ./wait-for-it.sh db:5432 -- python manage.py collectstatic --no-input &&
             gunicorn --workers ${GUNICORN_WORKERS:-9} --threads ${GUNICORN_THREADS:-4} --bind 0.0.0.0:8000 event_manager.wsgi:application"
    env_file:
      - .env.docker.prod
    depends_on:
      - db
    volumes:
      - static_volume:/app/static   # web кладe static сюди
    networks:
      - webnet

  nginx:
    image: nginx:stable-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - static_volume:/app/static:ro   # nginx читає static з того ж тому
      # - ./nginx/certs:/etc/letsencrypt/live:ro   # якщо certs локально (для HTTP-01)
    depends_on:
      - web
    networks:
      - webnet

volumes:
  postgres_data_prod:
  static_volume:

networks:
  webnet:
    driver: bridge
