# Generated by Django 5.2.1 on 2025-05-30 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_options_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Full name can only contain letters, numbers, spaces, hyphens, apostrophes, and periods.', regex="^[a-zA-Z0-9\\s\\-\\'\\.]+$")]),
        ),
    ]
