# Generated by Django 5.2.1 on 2025-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(help_text='Enter your name, pseudonym, or group name', max_length=100),
        ),
    ]
