# Generated by Django 5.2.1 on 2025-05-31 08:39

from django.db import migrations, models


def copy_full_name_to_username(apps, schema_editor):
    User = apps.get_model("users", "CustomUser")
    for user in User.objects.all():
        user.username = user.full_name
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_full_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.CharField(max_length=150, unique=True, null=True, blank=True),
        ),
        migrations.RunPython(copy_full_name_to_username),
    ]
